# Generated by Django 5.2.17 on 2026-08-20 15:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('FullAmount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='القسط الكلي')),
                ('PaidAmount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المدفوع')),
                ('Paymentresult', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المتبقي')),
                ('payment_type', models.CharField(default='full', max_length=20, verbose_name='نوع الدفع')),
                ('status', models.CharField(default='قيد التحصيل', max_length=20, verbose_name='حالة الحساب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ العملية')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='academics.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'المدفوعات',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='القيمة')),
                ('note', models.CharField(blank=True, default='', max_length=80, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.payment', verbose_name='الدفعة')),
            ],
            options={
                'verbose_name': 'حركة مالية',
                'verbose_name_plural': 'الحركات المالية',
                'ordering': ('-created_at',),
            },
        ),
    ]
