# Generated by Django 5.2.17 on 2026-08-20 15:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('special_number', models.CharField(max_length=10, verbose_name='الرقم المميز')),
                ('Nameofexam', models.CharField(max_length=80, verbose_name='اسم المذاكرة')),
                ('Subject_name', models.CharField(max_length=30, verbose_name='المادة')),
                ('Date', models.DateField(verbose_name='تاريخ التقديم')),
                ('Itsnote', models.CharField(blank=True, default='', max_length=80, verbose_name='ملاحظة')),
                ('Mark', models.IntegerField(verbose_name='العلامة')),
                ('Full_mark', models.IntegerField(verbose_name='العلامة الكاملة')),
                ('student', models.ManyToManyField(related_name='exams', to='academics.student', verbose_name='الطلاب')),
            ],
            options={
                'verbose_name': 'مذاكرة',
                'verbose_name_plural': 'المذاكرات',
                'ordering': ('-Date',),
            },
        ),
    ]
