# Generated by Django 5.2.17 on 2026-08-20 15:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25, unique=True, verbose_name='اسم المستخدم')),
                ('first_name', models.CharField(blank=True, max_length=15, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(blank=True, max_length=15, verbose_name='الكنية')),
                ('special_number', models.CharField(max_length=10, unique=True, verbose_name='الرقم المميز')),
                ('role', models.CharField(choices=[('manager', 'مدير'), ('teacher', 'أستاذ'), ('student', 'طالب')], default='student', max_length=16, verbose_name='الدور')),
                ('user_type', models.CharField(default='3', max_length=4, verbose_name='نوع المستخدم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_staff', models.BooleanField(default=False, verbose_name='طاقم')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('last_session_key', models.CharField(blank=True, default='', max_length=40)),
                ('token_version', models.PositiveIntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ والوقت')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='المتصفح/الجهاز')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل دخول',
                'verbose_name_plural': 'سجلات الدخول',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=15, verbose_name='الكنية')),
                ('special_number', models.CharField(max_length=7, unique=True, verbose_name='الرقم المميز')),
                ('user_type', models.CharField(default='1', max_length=4, verbose_name='نوع المستخدم')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مدير',
                'verbose_name_plural': 'المديرون',
            },
        ),
    ]
