# Generated by Django 5.2.17 on 2026-08-20 15:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_type', models.CharField(max_length=40, verbose_name='نوع الشهادة')),
                ('grade', models.CharField(max_length=30, verbose_name='الصف')),
                ('section', models.CharField(max_length=40, verbose_name='الشعبة')),
                ('day', models.CharField(max_length=20, verbose_name='اليوم')),
                ('time_slot', models.CharField(max_length=20, verbose_name='الحصة')),
                ('room', models.CharField(max_length=40, verbose_name='القاعة')),
                ('subject_name', models.CharField(max_length=30, verbose_name='المادة')),
                ('teacher_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='academics.teacher', verbose_name='الأستاذ')),
            ],
            options={
                'verbose_name': 'برنامج',
                'verbose_name_plural': 'البرامج',
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Day', models.DateField(verbose_name='اليوم')),
                ('Hour', models.TimeField(verbose_name='الساعة')),
                ('Subject', models.CharField(max_length=30, verbose_name='المادة')),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_tables', to='academics.teacher', verbose_name='الأستاذ')),
                ('student', models.ManyToManyField(related_name='time_tables', to='academics.student', verbose_name='الطلاب')),
            ],
            options={
                'verbose_name': 'حصة زمنية',
                'verbose_name_plural': 'الجدول الزمني',
                'ordering': ('Day', 'Hour'),
            },
        ),
    ]
