# Generated by Django 5.2.17 on 2026-08-20 15:33

import academics.files
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='اسم المرحلة')),
            ],
            options={
                'verbose_name': 'مرحلة',
                'verbose_name_plural': 'المراحل',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='اسم المادة')),
            ],
            options={
                'verbose_name': 'مادة',
                'verbose_name_plural': 'المواد',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=15, verbose_name='الكنية')),
                ('special_number', models.CharField(max_length=10, unique=True, verbose_name='الرقم المميز')),
                ('gender', models.CharField(blank=True, default='', max_length=10, verbose_name='الجنس')),
                ('teacher_number', models.CharField(max_length=10, verbose_name='رقم الهاتف')),
                ('expertise', models.CharField(max_length=30, verbose_name='المادة/الخبرة')),
                ('cv', models.CharField(blank=True, default='', max_length=175, verbose_name='السيرة')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to=academics.files.UUIDCVUploadTo(), validators=[academics.files.validate_cv_file], verbose_name='ملف السيرة')),
            ],
            options={
                'verbose_name': 'أستاذ',
                'verbose_name_plural': 'الأساتذة',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='اسم الشعبة')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.stage', verbose_name='المرحلة')),
            ],
            options={
                'verbose_name': 'شعبة',
                'verbose_name_plural': 'الشعب',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=15, verbose_name='الكنية')),
                ('special_number', models.CharField(max_length=10, unique=True, verbose_name='الرقم المميز')),
                ('student_class', models.CharField(max_length=20, verbose_name='الصف/المرحلة')),
                ('parent_number', models.CharField(max_length=10, verbose_name='هاتف الأهل')),
                ('student_number', models.CharField(max_length=10, verbose_name='هاتف الطالب')),
                ('address', models.CharField(max_length=30, verbose_name='عنوان السكن')),
                ('personal_notes', models.CharField(blank=True, default='', max_length=25, verbose_name='ملاحظات')),
                ('is_payer', models.BooleanField(default=False, verbose_name='مسدد')),
                ('class1', models.CharField(blank=True, default='', max_length=30, verbose_name='مادة 1')),
                ('class2', models.CharField(blank=True, default='', max_length=30, verbose_name='مادة 2')),
                ('class3', models.CharField(blank=True, default='', max_length=30, verbose_name='مادة 3')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.section', verbose_name='الشعبة')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.stage', verbose_name='المرحلة')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
            },
        ),
    ]
