# Generated by Django 5.2.17 on 2026-08-22 19:16

from django.db import migrations, models


def copy_class_slots(apps, schema_editor):
    Student = apps.get_model("academics", "Student")
    Subject = apps.get_model("academics", "Subject")
    for student in Student.objects.all():
        for name in (student.class1, student.class2, student.class3):
            name = (name or "").strip()
            if not name:
                continue
            subject, _ = Subject.objects.get_or_create(name=name[:30])
            student.subjects.add(subject)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_remove_student_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='students', to='academics.subject', verbose_name='المواد'),
        ),
        migrations.RunPython(copy_class_slots, noop),
    ]
