# Generated by Django 5.2.17 on 2026-08-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_student_subjects_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class1',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='المرحلة والفرع'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class2',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='المواد'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class3',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='الشعبة'),
        ),
    ]
